{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ilm-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ilm-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ilm-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
