/*
Copyright The ILM Authors.

SPDX-License-Identifier: Apache-2.0
*/

package platform

import (
	"strconv"

	otilmv1alpha1 "github.com/OmniTrustILM/operator/api/v1alpha1"
	"github.com/OmniTrustILM/operator/internal/builder/common"
	"github.com/OmniTrustILM/operator/pkg/bom"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

const (
	// timeQualityMonitorComponent is the bundle component key AND the container name of the
	// time-quality-monitor sidecar.
	timeQualityMonitorComponent = "time-quality-monitor"
	// timeQualityMonitorPort is the port the monitor listens on and serves /health from.
	timeQualityMonitorPort int32 = 8082
	// timeQualityMonitorListenPortEnv / timeQualityMonitorLogLevelEnv are the monitor IMAGE's
	// own configuration contract (not platform wiring, which is why they are not in the version
	// bundle's WiringProfile) — the same way opaSidecar carries OPA's own flags.
	timeQualityMonitorListenPortEnv = "LISTEN_PORT"
	timeQualityMonitorLogLevelEnv   = "LOG_LEVEL"
	// timeQualityMonitorHealthPath is the monitor's health endpoint, used for both probes.
	timeQualityMonitorHealthPath = "/health"
)

// TimeQualityMonitorEnabled reports whether the Core pod carries the time-quality-monitor
// sidecar: the CR asks for it AND the selected version bundle carries the monitor image.
//
// The bundle gate makes the same CR portable across versions — the monitor image is a 2.19.0
// component, so a platform pinned to an older version simply renders no sidecar instead of
// referencing an image that release never had (the same version-gating ProvisioningDeploy
// applies to the bundled provisioning service).
func TimeQualityMonitorEnabled(p *otilmv1alpha1.Platform) bool {
	m := p.Spec.Core.TimeQualityMonitor
	if m == nil || !m.Enabled {
		return false
	}
	_, ok := resolveBundle(p).Lookup(timeQualityMonitorComponent)
	return ok
}

// timeQualityMonitorPullSecrets returns the sidecar's own image pull secrets, for the POD-level
// union in ResolveCore — and NOTHING when the sidecar does not render.
//
// The gate is load-bearing, not tidiness: imagePullSecrets is a POD field, so an ungated helper
// would change Core's pod TEMPLATE (and therefore ROLL Core) for a monitor that is switched off
// or whose bundle carries no monitor image. A sidecar's private image cannot be pulled with a
// container-scoped credential, which is why the secrets have to reach the pod at all when it
// DOES render.
func timeQualityMonitorPullSecrets(p *otilmv1alpha1.Platform) []string {
	if !TimeQualityMonitorEnabled(p) {
		return nil
	}
	return p.Spec.Core.TimeQualityMonitor.Image.PullSecrets
}

// TimeQualityMonitorCredentialsSecretName returns the name of the Secret the monitor sidecar
// reads its broker credentials from, or "" when no sidecar renders. It is exported for the
// controller's Secret WATCH: in managed messaging that Secret is generated by the Messaging
// Topology Operator, so the watch is what re-enqueues the Platform the moment it appears.
// NAME only — no value is ever read here.
func TimeQualityMonitorCredentialsSecretName(p *otilmv1alpha1.Platform) string {
	if !TimeQualityMonitorEnabled(p) {
		return ""
	}
	secret, _, _ := timeQualityMonitorCredentials(p)
	return secret
}

// timeQualityMonitorCredentials resolves the Secret the monitor authenticates to the broker
// with, and the in-Secret keys holding the username and password:
//
//   - MANAGED messaging → the Messaging-Topology-Operator-generated monitor-USER Secret, with
//     the upstream operator's key convention (which matches the wiring defaults). A bundle
//     whose topology has no monitor role (2.17.0) yields an empty Secret name.
//   - EXTERNAL messaging → the CR's own credentials.secretRef, with the user's key overrides
//     when set (the CEL rule makes the reference mandatory there).
//
// SECURITY: this returns NAMES only. The values are projected by secretKeyRef and are never
// read, copied, logged, or placed in status.
func timeQualityMonitorCredentials(p *otilmv1alpha1.Platform) (secret, usernameKey, passwordKey string) {
	w := wiringFor(p)
	if MessagingManaged(p) {
		if !resolveBundle(p).Messaging.HasUserRole(bom.MessagingUserMonitor) {
			return "", "", ""
		}
		return managedUserCredentialsSecretName(p, bom.MessagingUserMonitor),
			w.MessagingCred.UsernameKey, w.MessagingCred.PasswordKey
	}
	var creds *otilmv1alpha1.CredentialsRef
	if m := p.Spec.Core.TimeQualityMonitor; m != nil {
		creds = m.Credentials
	}
	return credentialsSecretRef(creds), msgCredUsernameKey(creds, w), msgCredPasswordKey(creds, w)
}

// timeQualityMonitorSidecar renders the time-quality-monitor container: the bundle's private
// image, the monitor's listen port and log level, the broker coordinates (host/port from the
// shared messaging ConfigMap, vhost from the resolved connection, credentials by secretKeyRef),
// and the chart's /health liveness + readiness probes. The common BuildDeployment path
// SCC-hardens it like every other container.
//
// Read-only root filesystem: ENABLED. The monitor serves HTTP and talks AMQP; it writes nothing
// to disk.
func timeQualityMonitorSidecar(p *otilmv1alpha1.Platform) corev1.Container {
	w := wiringFor(p)
	var spec otilmv1alpha1.TimeQualityMonitorSpec
	if m := p.Spec.Core.TimeQualityMonitor; m != nil {
		spec = *m
	}
	image, policy := common.ResolveImage(resolveBundle(p).Lookup, timeQualityMonitorComponent,
		p.Spec.Common.Image, spec.Image)

	logLevel := p.Spec.Common.Logging.Level
	if logLevel == "" {
		logLevel = defaultLogLevel
	}

	env := []corev1.EnvVar{
		{Name: timeQualityMonitorListenPortEnv, Value: strconv.Itoa(int(timeQualityMonitorPort))},
		{Name: timeQualityMonitorLogLevelEnv, Value: logLevel},
		{Name: w.MessagingHostEnv, ValueFrom: &corev1.EnvVarSource{ConfigMapKeyRef: &corev1.ConfigMapKeySelector{
			LocalObjectReference: corev1.LocalObjectReference{Name: w.MessagingConfigMapName},
			Key:                  w.MessagingHostKey,
		}}},
		{Name: w.MessagingPortEnv, ValueFrom: &corev1.EnvVarSource{ConfigMapKeyRef: &corev1.ConfigMapKeySelector{
			LocalObjectReference: corev1.LocalObjectReference{Name: w.MessagingConfigMapName},
			Key:                  w.MessagingPortKey,
		}}},
		{Name: w.MessagingVHostEnv, Value: ResolveMessagingConnection(p).VirtualHost},
	}
	if secret, userKey, passKey := timeQualityMonitorCredentials(p); secret != "" {
		env = append(env,
			corev1.EnvVar{Name: w.MessagingCred.UsernameEnv, ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: secret}, Key: userKey,
			}}},
			corev1.EnvVar{Name: w.MessagingCred.PasswordEnv, ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: secret}, Key: passKey,
			}}},
		)
	}

	probe := &corev1.Probe{
		ProbeHandler: corev1.ProbeHandler{
			HTTPGet: &corev1.HTTPGetAction{
				Path:   timeQualityMonitorHealthPath,
				Port:   intstr.FromInt32(timeQualityMonitorPort),
				Scheme: corev1.URISchemeHTTP,
			},
		},
		InitialDelaySeconds: 5,
		TimeoutSeconds:      5,
		PeriodSeconds:       10,
		SuccessThreshold:    1,
		FailureThreshold:    3,
	}

	ctr := corev1.Container{
		Name:            timeQualityMonitorComponent,
		Image:           image,
		ImagePullPolicy: policy,
		// The sidecar honours image.command / image.args like every other component with a
		// user-facing ImageSpec, through the same shared-then-component precedence
		// (imageCommand / imageArgs). It is wired HERE rather than in common.BuildDeployment
		// because that only shapes the MAIN container: a sidecar is handed over fully formed.
		Command:         imageCommand(p.Spec.Common.Image, spec.Image),
		Args:            imageArgs(p.Spec.Common.Image, spec.Image),
		Ports:           []corev1.ContainerPort{{ContainerPort: timeQualityMonitorPort}},
		Env:             env,
		LivenessProbe:   probe,
		ReadinessProbe:  probe.DeepCopy(),
		SecurityContext: &corev1.SecurityContext{ReadOnlyRootFilesystem: readOnlyRootFS()},
	}
	if spec.Resources != nil {
		ctr.Resources = *spec.Resources
	}
	return ctr
}
